### ISSUE TITLE
Predictive accuracy increasing over all values of K from X-Val

### ISSUE THREAD

**Issue by alex-sandercock** [gbradburd/conStruct#45]
Hi,

I performed the cross-validation for a dataset of 71 individuals and ~88k SNPs. It seems that the predictive accuracy steadily increases until it approaches 0 at the highest value of K used in the analysis.

I had previously checked this dataset in ADMIXTURE and DAPC for population structure and both suggest K=1, and when I check the layer contributions in conStruct, it supports K=1. So, what could be the reason that I am not seeing the cross-validation figure plateauing at K=1?

Thank you for your help!

Alex
<img width="769" alt="Screen Shot 2021-11-01 at 2 02 55 PM" src="https://user-images.githubusercontent.com/39815775/139718862-66fb42b4-c075-4fc5-af42-0772c4ecfa18.png">
<img width="502" alt="Screen Shot 2021-11-01 at 2 03 13 PM" src="https://user-images.githubusercontent.com/39815775/139718875-d847550f-302d-4522-940d-3a8655c3b03b.png">

**Comment by alex-sandercock** [comment]
Thank you for such a quick and detailed reply!

I had performed fairly aggressive LD pruning in plink (50 bp window, 10 bp slide, R^2 = 0.1), but maybe this wasn't enough.

I'll stick with the layer contributions, though, can I still correctly assume that IBD is a feature of the dataset from the cross-validation plot? Or should the cross-validation plot as a whole not be given much focus in this situation.

Thanks again,

Alex

**Comment by gbradburd** [comment]
Yeah I guess I'd say that if you're going with the layer contributions because you're not sure whether to trust the cross-validation procedure, you can't really use the cross-validation results to support your arguments elsewhere.  If you want to make a more quantitative statement about IBD in your data (other than just looking at pairwise relatedness plotted against pairwise geographic distance), you could look at the shape of the IBD curve inferred for the layer (or the distribution of the _alphaD_ parameter).

**Comment by alex-sandercock** [comment]
Sounds good, I'll check that out.

Alex
