### ISSUE TITLE
Most differentiated samples grouped in the same layer 

### ISSUE THREAD

**Issue by norabergman** [gbradburd/conStruct#48]
Dear Gideon,

first of all, thanks for the wonderful software and documentation. I'm facing a situation where the spatial model groups genetically most differentiated samples/populations in the same layer. You described this possibility also in the original publication, mentioning that it can result from shared demographic history but also from certain values of the layer-specific parameters. 

In my case, shared demographic history for these grouped populations would be very surprising. What would be the best way to further explore and understand what is causing this result and whether it really has biological significance?

I'll attach details of my analyses below:

171 individuals, ~52 000 SNPs
Spatial and non-spatial analysis with train.prop = 0.9, n.reps = 4, K = 1:4, n.iter = 5000. Trace plots look OK.

<img width="259" alt="sp_nsp_cross-validation" src="https://user-images.githubusercontent.com/113015878/188838453-dba69dc8-9d2e-44e8-9293-6bceb9a351cb.PNG"> 

Spatial analysis supporting K=2, which groups the most northern and southern samples to the same layer (even with K=3 or K=4 these samples don't split out to different layers):
<img width="280" alt="layer_contr_sp" src="https://user-images.githubusercontent.com/113015878/188841034-c73a0036-5ae0-4ef1-935b-1e279308b6f1.PNG"> <img width="230" alt="sp_k2" src="https://user-images.githubusercontent.com/113015878/188841060-31116029-a36b-4a57-a3f7-d27ae38d4984.PNG">

Non-spatial analysis with K=3, reflecting the known, quite continuous genetic differentiation (likely mostly caused by IBD) in the samples:
<img width="275" alt="layer_contr_nsp" src="https://user-images.githubusercontent.com/113015878/188841112-1a674bd1-33fe-43dd-89f0-2b3d99c0f24f.PNG"> <img width="230" alt="nsp_k3" src="https://user-images.githubusercontent.com/113015878/188841140-083571b6-a6be-485b-a04f-12b5c91fa04d.PNG">

**Comment by gbradburd** [comment]
Hmm this is a tricky one.  So the spatial model is lumping the northernmost & southernmost samples into the same layer (and explaining their divergence using the large distance between them), while the non-spatial model is splitting them out into different discrete groups? And, it sounds like you think that the shared ancestry implied by membership in the same layer between these N and S samples is biologically implausible (although maybe not because you’re saying that the structure in the nonspatial K=3 model is caused by isolation by distance?)?

Big picture, I think that this issue kind of reflects a difference of priors.  The spatial model wants to explain divergence using a model of IBD and the distance between samples, and only invokes multiple discrete layers when it can’t do that.  In this case, it sounds like your prior belief is that gene flow between the N&S samples isn't/hasn't been that likely, and that the divergence between them is better explained by invoking discrete ancestral populations that aren't well connected.  If that's the case, and you have good biological/geological reasons to back up that intuition, then I think it's totally reasonable to use the results of a nonspatial model over conStruct's spatial model.  These models are all cartoons of reality anyway, and though some may give more or less valuable insight in different scenarios, none of them is ever actually correct.

One concrete thing to check is the "shared drift" phi parameter in that red layer in spatial model with K=2.  That term governs the baseline amount of relatedness between any two samples with 100% membership in the layer, regardless of the geographic distance between them.  So, if that number is really small, it's more likely that the N&S samples being placed in the same layer doesn't mean that much.  If it's large, that would indicate that those N&S samples have some meaningful relatedness, making their placement in the same layer less likely to be a model artifact.

Hope that's helpful!
-Gideon

**Comment by norabergman** [comment]
Thank you so much for the quick and detailed reply, definitely helpful! 

Yes, I was a bit unclear in my wording: shared ancestry between the N&S samples would not be biologically implausible (there seems to be no strong barriers for gene flow in the studied range). However, we know that the northern (Fennoscandic) sites were first colonized ~100 years ago, and other evidence (historical observations, migratory direction, genetic relatedness) suggest that the area was colonized from southwest rather than southeast. It's not impossible that gene flow has occurred also between the northern and southeastern sites (or to both from an unsampled, more eastern population), but I would like to understand and be able to discuss this quite unexpected result as well as possible.

The phi parameter for the spatial model with K=2 varies slightly between the chains, being approximately in the same magnitude for the two layers or slightly higher in layer 2. E.g. in chain 1: phi=3.49e-06 for layer 1 and phi=1.11e-05 for layer 2. Would it be useful to compare these values to the ones in the non-spatial model, or what would be the best way to determine whether they are large or small?

Best,
Nora

**Comment by gbradburd** [comment]
I had been thinking you could compare values of phi between the two layers.  If the blue layer's phi was much larger than the red layer's phi (in the spatial model results you included in your original post), that could be an indication that the shared membership in the red layer was maybe spurious (or, perhaps better to say, less biologically meaningful).  Both those values seem pretty small, but I guess it's relative to the overall degree of relatedness between your samples.

**Comment by norabergman** [comment]
Ok! I'll continue figuring out the meaning of the result, as it at least doesn't show obvious signs of being a model artifact or of negligible biological significance. Many thanks for your help and insights!
