### ISSUE TITLE
Messy data with lots of errors..

### ISSUE THREAD

**Issue by qthomas612** [gbradburd/conStruct#50]
Hello Giideon and Peter, 

Apologies in advance for the long message. I'm hoping to give all the context to help understand the issues I'm having.

Background: I'm working with ddRAD-Seq data where I have approx. 490 snps for ~200 plants from 18 varieties sampled across 70 locations in Southwest USA. I know this is very few snps for a very large number individuals. I exported snps from stacks in a structure format file and converted them to conStruct file format successfully. I've used these snps in structure and adegenet. The structure results look ok with most individuals clustering according to the location they were sampled at. However, PCA in adegenet didn't show the best clustering with a lot of sites/varieties overlapping with one another and the first PC explaining only 10% of the variation. 
 
My first issues arise when I try to run conStruct with both spatial and non-spatial analysis.
> "Error in pos.def.check(obsCov)". 

Fair enough, I have a lot of individuals with missing data and not that many snps. I filtered my dataset to only 70 individuals with the max missing data being 25% and I still receive this error. I can't seem to identify any one or pair of individuals that is causing this.

As for the next issue, I've only been able to run conStruct with a subset of 40 individuals at a time. After running conStruct I receive the following warning messages:
> "There were 306 divergent transitions after warmup." I don't think I've ever had a run with less than 280 divergences
> R-hat too large (2.23) 
> bulk and tail ESS being too low.

When I run with K = 1 the only warning I get is for tail ESS being too small

I've looked into your other threads for these topics and have tried the following with no luck
-increasing n.iter to 100000
-increasing adapt_delta to 0.99
I have attached the trace plots and I'm not sure I am interpreting them correctly but they don't seem comparable across chains?

Last issue!  When I am able to run construct, the dimensions of my allele freq matrix is 41 x 489 however the data block is reading 185 loci. My assumption is that it's dropping 300 of my loci that it's reading as invariant but when I run `unique(allele_freqs, MARGIN=2) ` I'm retaining 440 loci. Is this likely because of missing data? I have attached my subset data as well. 

Please let me know if there is any other information that I can provide. Thank you for your diligence on this forum!

[_trace.plots.chain_1.pdf](https://github.com/gbradburd/conStruct/files/10468109/_trace.plots.chain_1.pdf)
[_trace.plots.chain_2.pdf](https://github.com/gbradburd/conStruct/files/10468110/_trace.plots.chain_2.pdf)
[_trace.plots.chain_3.pdf](https://github.com/gbradburd/conStruct/files/10468202/_trace.plots.chain_3.pdf)

[subset_allele_freq.Robj.zip](https://github.com/gbradburd/conStruct/files/10468201/subset_allele_freq.Robj.zip)

**Comment by gbradburd** [comment]
Hello!

Ok it seems like you have 3 questions/issues:

1. non-positive definiteness.  This is a tricky one, and is likely arising from, as you guessed, non-random missingness of data.  I usually recommend dropping the individuals with the most missing data, followed by the loci with the most missing data, and working my way down until I have a viable dataset.  It might be that if you drop the individuals with the highest proportion of missing data, you can get away with having a less strict missing data cut-off per locus.  This is related to...

2. conStruct dropping loci. This is happening because once you've reduced your dataset from ~200 to the 41 in your `subset_half_sites` matrix, those sites are no longer variable (if you exclude missing data).  E.g., in the 2nd locus in your dataset, the values are all either `1` or `NA`.   Out of your 489 loci, 304 of them are invariant in your subset.

3. mixing.  Chain 1 actually looks pretty good to me, but the other two don't look great (and look like they should be run longer, given that the posterior probability still seems to be climbing?).  In general, I would recommend worrying less about the warnings about ESS and divergent transitions, and more about getting trace plots that look good within each chain and consistent across chains.  Here, I would have recommended running the chains longer, but 1e4 iterations is a lot, so I'd be surprised if increasing the number of iterations substantially improves mixing.  It's possible that you simply don't have enough information in your data to effectively parameterize the model.  Once you've removed the invariant sites in this data subset, it looks like over 75% of your variants are singletons, so there's not a huge amount of information about how individuals are related to each other in your dataset.  I'm sorry I don't have more concrete advice to offer here!

hope that helps!
-Gideon

**Comment by qthomas612** [comment]
Hi Gideon, 

Thank you for responding so quickly. We are working with a preliminary dataset and are hoping to get data from a better sequencing run with more SNPs so I am hoping that will help to resolve some of the issues we are facing. I would have liked to have been more strict with the filtering but because we were already struggling for snps I didn't want to filter the data too much given the amount of individuals and populations we were dealing with. 

For the time being I think we will wait to explore with this further until our new data comes in. I will be sure to ask if any more issues arise.

Thanks,
Quinn

**Comment by gbradburd** [comment]
Ok sounds good Quinn!  I'm going to close the issue for now, but feel free to reopen (or start a new issue) if you run into more hiccups down the line.
